/*
 * This source file was generated by the Gradle 'init' task
 */
package org.kalkulator;

import org.junit.jupiter.api.Test;
import org.kalkulator.Main;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
